### ISSUE TITLE
Skip parameters

### ISSUE THREAD

**Issue by AvrumFeldman** [jeremmfr/iptables-api#2]
Any way to skip parameters that are not needed for the rule?

For example I'm trying to create a rule to block port 53 inbound, the iptables command for that would be 
```
iptables -t filter -I INPUT -p udp --dport 53 -j DROP
```

Per the example is saw in issue https://github.com/jeremmfr/iptables-api/issues/1 I should be able to ignore interfaces by providing a `+`. But when I attempted to that I got a 404
```
http://192.168.145.143:8443/rules/DROP/INPUT/tcp/+/+/0.0.0.0_0/0.0.0.0_0/&dport=53
```

But when I excluded the `&dport=53` I got an iptables error and from that error I was able to deduct that the plus sign does get forwarded to iptables. The error I get is
```
Invoke-RestMethod: running [/usr/sbin/iptables -t filter -A INPUT -p tcp -s 0.0.0.0/0 -d 0.0.0.0/0 -j DROP -i + -o + --wait --wait]: exit status 2: iptables v1.8.4 (legacy): Can't use -o with INPUT    
Try `iptables -h' or 'iptables --help' for more information.
```

Regardless, it can't seem to figure out a way to create a new INPUT rule without specifying interfaces.

**Comment by jeremmfr** [comment]
Hello,

You can ignore the interface parameters if you use `*` see https://github.com/jeremmfr/iptables-api/blob/v1.17/rules.go#L34.
This skip isn't implemented in the nat function, so `+` is used and understood by iptables.
